const interviewerData = [
  {
    id: 1,
    no: "Interview01",
    src: "/interview01.png",
    alt: "interview01の画像",
    position: "QA Engineer",
    position2: "Director",
    name: "Ms.Yadanar Kyaw Khaing",
    date: "(Joined in 2018)",
    mv_src1: "/_single.jpg",
    mv_src2: "/_uniform.jpeg",
    q1: "Please share your current job responsibilities at Qualy Myanmar.",
    ans1: "I'm currently living in Japan and telework with Qualy Myanmar side, primarily focusing on management tasks. My responsibilities include from developing necessary test cases at project initiation to overseeing project management until completion. Throughout the project testing period, I provide support to team members to ensure smooth testing processes. Additionally, I am accountable for client communication. In addition to project-related duties, I participate in brainstorming sessions for company growth and attend other meetings as required",
    q2: "How you started working at Qualy Myanmar?",
    ans2: "My university colleague, who works at Qualy Myanmar, introduced me to the company, and I decided to join because I really liked the atmosphere there.",
    q3: "What is the working  atmosphere like at Qualy Myanmar?",
    ans3: "Our company's working culture is inclusive and supportive, regardless of your level of experience in Quality Assurance (QA). Seniors provide mentoring to help newcomers become reliable team members. There's a transparent atmosphere where everyone, can freely express their thoughts and opinions. Based on your performance, you have the opportunity to advance from an entry-level position to a higher one that suits you. From my perspective, there are various career paths to explore within the company. Additionally, the company organizes monthly birthday parties and seasonal festivals, such as the Waso Robe offering festival, Kahtein Festival, and Thingyan Festival, providing opportunities for enjoyment and celebration alongside work.",
    q4: "Please explain the roles and responsibilities of Quality Assurance？",
    ans4: "QA (Quality Assurance) involves identifying and resolving bugs in web and mobile products. We report these bugs to the development teams to ensure the products are bug-free before, during, and after release. We test the products on various real devices likes smartphones, tablets, and MacBooks, to ensure they function properly without any issues.",
    q5: "What kind of person do you think is suitable for the role of Quality Assurance？",
    ans5: "I think people with a moderate understanding of IT are well-suited for QA positions. It's important to thoroughly check details and report bugs clearly to the development team. Additionally, a passion for problem-solving, clear communication skills, and adaptability are essential qualities for this role. Furthermore, there are various types of projects and it’s important to be flexible depending on the project conditions. I think those kind of people are suitable for QA position.",
    q6: "Could you share an experience when you felt particularly motivated and fulfilled by your work?",
    ans6: "The company was in the startup situation when I joined, but it has grown since then, now employing around 80 people. I feel satisfied with my role as a founding member, having been part of the company's journey from its beginning. Furthermore, I’m also passionately interested in the Japanese language, and using the Japanese language for discussing with native Japanese people during meetings improves my Japanese language skills, logical thinking and gain some other precious knowledge. I've also had the opportunity to test services that are not yet available in Myanmar and I feel proud and delighted when I see the digital products that we’ve been tested out are used in Japan.",
    q7: "What are your future goals?",
    ans7: "My goal is to continue collaborating and working with Qualy Myanmar through our current phase and beyond, aiming to see us grow to over 200 employees.",
  },
  {
    id: 2,
    no: "Interview02",
    src: "/myo_capture.png",
    alt: "myo_captureの画像",
    position: "QA Engineer",
    position2: "Team Leader",
    name: "Ms.Myo Thandar Aye",
    date: "(Joined in 2018)",
    mv_src1: "/myo_single.jpg",
    mv_src2: "/myo_uniform.jpeg",
    q1: "Please share your current job responsibilities at Qualy Myanmar.",
    ans1: "I’m working as a team leader in the QA ( Quality Assurance) department at Qualy Myanmar. Currently, I’m managing my team members and also working as a tester together with my team members for updating the websites, and also do checking for the Apps and Websites that have not been released yet.",
    q2: "How you started working at Qualy Myanmar?",
    ans2: "I was introduced about the company by a sister who’s working at Qualy Myanmar. As it's a foreign Japanese company, I saw it as an opportunity to gain technical experience and understand their working style, so I decided to join. The company's location is also conveniently close to my home.",
    q3: "What is the working  atmosphere like at Qualy Myanmar?",
    ans3: "All team members respect each other and actively participate in teamwork creating a warm enviroment to work. We receive appreciation and praise for our successes. If there are any workplace difficulties, you don't have to solve them alone. Problems are solved by collaborating with superiors and directors, fostering a supportive relationship among employees. We wear uniforms every Wednesday, but on other days, we can dress casually and enjoy the day.",
    q4: "Please explain the roles and responsibilities of Quality Assurance？",
    ans4: "The responsibility of a QA position is to seek and check for bugs whether the systems meet the specifications and are easy to use without any problems by performing various kinds of verifications from the user’s point of view. We also have to report not only the discovered bugs but also the proposals as a user to our clients.",
    q5: "What kind of person do you think is suitable for the role of Quality Assurance？",
    ans5: "People who can collaborate with the team, can give suggestions related to work, are capable of focusing on work patiently, have a quick response with good communication and those who never tired of detailed work without never ignoring mistakes are well-suited for the QA position.",
    q6: "Could you share an experience when you felt particularly motivated and fulfilled by your work?",
    ans6: "When we can report not only the bugs but also the suggestions to the client side and the client also accepts our suggestions and our clients say “Thank you so much for your hard work “ at the end of a project, I feel satisfied and glad with my efforts,which boosts my self-confidence. Additionally, when the subject matters that I've shared to my team members are beneficial in their daily workplace.",
    q7: "What are your future goals?",
    ans7: "Even though I'm currently working in management, I'm actively learning from my superiors to improve my ability to manage more members. I'm also improving my Japanese language skills to a business level. I aim to become proficient enough to effectively communicate and interact with Japanese Clients during business meetings.",
  },
  {
    id: 3,
    no: "Interview03",
    src: "/hpw_capture.jpg",
    alt: "hpw_captureの画像",
    position: "QA Engineer",
    position2: "Team Leader",
    name: "Ms.Hnin Phyo Wai",
    date: "(Joined in 2019)",
    mv_src1: "/hpw_single.png",
    mv_src2: "/hpw_uniform.jpeg",
    q1: "Please share your current job responsibilities at Qualy Myanmar.",
    ans1: "I’m currently working as a team leader in the QA department at Qualy Myanmar. My responsibilities include overseeing team management and progress tracking. I also participate in testing with my team members when needed. We have to test the websites and Apps that have not been launched as well as the already launched websites and Apps.",
    q2: "How you started working at Qualy Myanmar?",
    ans2: "After graduating, I moved to Yangon to search for a job. Since I had no experience in IT, finding employment was challenging. Fortunately, a friend introduced me to Qualy Myanmar, an IT company located in Mawlamyine which is near my hometown city. The company welcomes no experience freshmen and offers free Japanese language support programs from the basic level. This led me to join Qualy Myanmar.",
    q3: "What is the working  atmosphere like at Qualy Myanmar?",
    ans3: "In our company, there are experienced seniors who mentor effectively. The working environment is warm and you can get as many opportunities as you try. Starting as a member, you can progress to higher positions like project leader, sub-leader, and manager based on performance. Additionally, all members have opportunities for free technical skill-up training in Japan, fully funded by our CEO. It was a valuable experience to gain new foreign experience during my one-month training in Japan.",
    q4: "Please explain the roles and responsibilities of Quality Assurance？",
    ans4: "QA ( Quality Assurance ) means the guarantee of the quality. To say it in simple and understandable way, QA involves testing websites and applications to find and fix bugs. We report these bugs to developers and can also offer suggestions based on our findings. QA includes both manual and automation testing. Currently, our company focuses on manual testing. Among black box testing and white box testing, our company specializes in black box QA testing. Black box testing is checking whether the external design and functions of the applications and websites meet the standards and the performance of the setting functions are doing well.",
    q5: "What kind of person do you think is suitable for the role of Quality Assurance？",
    ans5: "I think people those who have sense related to the inconvenience parts for users while using the websites and applications, and who also have the ideas and opinions like “ updating this part will make it easier for users to use” are suitable for the QA position. As QA is for finding errors and bugs, it’s important to keep in mind that “I’m finding the errors, I must find the bugs” and always need to think about what kind of testing methods can find the bugs. If testing with a positive mindset, it’s difficult to visible issues.",
    q6: "Could you share an experience when you felt particularly motivated and fulfilled by your work?",
    ans6: "I feel a sense of satisfaction when the applications and websites I've tested are completed smoothly before the deadline, receive positive feedback from clients, and I receive notifications about their release. It's in these moments that I feel I've done my best.",
    q7: "What are your future goals?",
    ans7: "As a current team leader, I am actively striving to progress to the role of team manager. In terms of management, my goal is to efficiently oversee and guide a team of over 20 members without encountering any difficulties within the next 1 to 2 years.",
  },
  {
    id: 4,
    no: "Interview04",
    src: "/mmt_capture.JPG",
    alt: "mmt_captureの画像",
    position: "QA Engineer",
    position2: "Team Member",
    name: "Ms.Myat Maw Thin",
    date: "(Joined in 2022)",
    mv_src1: "/mmt_single.jpg",
    mv_src2: "/mmt_uniform.jpeg",
    q1: "Please share your current job responsibilities at Qualy Myanmar.",
    ans1: "As a member of the QA Department, our day typically begins with a morning meeting to discuss project updates. Following the meeting, we commence work on our assigned projects for the day. Sometimes, when the project leader took leave day, I was responsible for the project and manage to continue without any difficulties. When new team members join our team, I have to train them on workplace protocols that basic points they should know when working and project specifics. Additionally, I continuously seek guidance from senior colleagues to improve my skills and progress from my current member position.",
    q2: "How you started working at Qualy Myanmar?",
    ans2: "One of my friends, who works at Qualy Myanmar, shared the company`s job post with me on Facebook. I applied and joined the company because I believe I can gain valuable experiences and learn new things from working at a foreign-based company like Qualy Myanmar.",
    q3: "What is the working  atmosphere like at Qualy Myanmar?",
    ans3: "There are a lot of intelligent seniors who guide and mentor carefully to their juniors. We value open discussion and opinion sharing, with seniors patiently listening and providing answer what is possible or impossible with specific reasons. We have `Weekly Meeting' every Wednesday includes icebreaker presentations and team reports, encouraging public speaking confidence and improving presentation skills.",
    q4: "Please explain the roles and responsibilities of Quality Assurance？",
    ans4: "As a Quality Assurance(QA), we have to check the Applications and websites whether the designs are displayed according to the design specifications, to test all the setting functions are stable and their processes are correctly working step by step according to specification. Depending on the various projects, we test both unreleased and already launched applications and websites. Therefore, it's essential to remember and follow basic rules before starting a project and during the testing period. We must focus to avoid leaking information from one project to another and follow the rules requested by the client as QA testers.",
    q5: "What kind of person do you think is suitable for the role of Quality Assurance？",
    ans5: "People who can express their own opinion to others in understandable way and fond of using various kinds of Apps and websites by their own, and people who have strong focus are suitable for QA position. Since QA is the work that requires cooperation with teams, we need good communication, critical thinking, innovation, and adaptability to different projects.",
    q6: "Could you share an experience when you felt particularly motivated and fulfilled by your work?",
    ans6: "I feel proud and grateful for the times when I successfully solved difficult bugs, provided valuable support to my seniors, and collaborated with my team to complete projects on time. Furthermore, our company provides evaluation awards ceremony every 6 months and I also have won one of the awards once. At that time, I felt so glad and proud to be appreciated and recognized by the superiors.",
    q7: "What are your future goals?",
    ans7: "Even though I'm currently a team member, I aim to achieve proficiency in Japanese and become a reliable leader who can assist directors soon. I also aspire to work in Japan to gain valuable experience. Therefore, I'm working hard and learning steadily to achieve for my vision.",
  },
  {
    id: 5,
    no: "Interview05",
    src: "/hlo_capture.jpg",
    alt: "hlo_captureの画像",
    position: "FrontEnd Engineer",
    position2: "Team Leader",
    name: "Mr.Htet Lin Oo",
    date: "(Joined in 2021)",
    mv_src1: "/hlo_single.jpg",
    mv_src2: "/hlo_uniform.jpg",
    q1: "Please share your current job responsibilities at Qualy Myanmar.",
    ans1: "I’m currently working as a web developer with the position of team leader of the Frontend department at Qualy Myanmar. Our team is responsible for doing website development and maintenance of websites by using HTML, CSS, JavaScript, jQuery, PHP, and WordPress on the designs.",
    q2: "How you started working at Qualy Myanmar?",
    ans2: "When I was looking for a job, since it was during the Covid pandemic period, and I also didn't have any experience, so it was difficult for me to find a job. At that time, I saw that Qualy Myanmar was calling for web developer position on Facebook, and even those who have no experience can also apply, therefore I applied for this job. I’ve started to join this job because the company permitted work from home during the COVID-19 pandemic period and the job also matches with my career.",
    q3: "What is the working  atmosphere like at Qualy Myanmar?",
    ans3: "At our company, employees are in good communication and also do their relevant job responsibly.  We have the opportunity to advance position up to sub-leader, leader, manager, and director levels based on performance. The company also provides and supports free Japanese classes and necessary coding courses to employees during working hours. So,we can improve our skills during working hours, and since there isn't much overtime compare to other IT companies, we can spend our free time pursuing hobbies and interests. This balanced approach helps maintain a healthy Work-Life balance.",
    q4: "Please explain the roles and responsibilities of Frontend Web Developer？",
    ans4: "The role of a web developer involves creating new designs and managing maintenance website for clients using HTML, CSS, JavaScript, jQuery, PHP, and WordPress. Our focus is not only on ensuring responsive design for compatibility across different devices and screen sizes, and optimizing website performance for faster loading times and smoother user experience, but also on meeting the specific needs of our clients.",
    q5: "What kind of person do you think is suitable for the role of Frontend Web Developer？",
    ans5: "I think people who are interested in websites development and design. Since the websites are created in various designs, and if there are any errors we need to think in various kinds of ways to solve them. So, people who are good at logical thinking and computational thinking, and solving the websites issues and errors are well-suited for Frontend Developer Job.",
    q6: "Could you share an experience when you felt particularly motivated and fulfilled by your work?",
    ans6: "I feel delighted when the websites we create are user-friendly upon launch. Through my experience as a front-end developer, I have improved my skills and gained valuable expertise in creating websites with various designs. I am grateful for the opportunity to work in such a dynamic and creative field.",
    q7: "What are your future goals?",
    ans7: "My future vision is to be able to work as a Chief Technology Officer of company.",
  },
  {
    id: 6,
    no: "Interview06",
    src: "/tsb_capture.jpg",
    alt: "tsb_captrueの画像",
    position: "Japanese Teacher",
    name: "Thin Sabai",
    date: "(Joined in 2022)",
    mv_src1: "/tsb_single.jpg",
    mv_src2: "/tsb_uniform.jpg",
    q1: "Please share your current job responsibilities at Qualy Myanmar.",
    ans1: "I currently teach Japanese language classes ranging from N5 to N3 levels at JTCM Japanese Language School. In addition to teaching, I introduce Japanese culture to my students and provide the training to students who are going to have interviews and who already passed the interview to work in Japan. On the other hand, I interpret the documents and also assist on post contents for Facebook page if necessary.",
    q2: "How you started working at Qualy Myanmar?",
    ans2: "I was introduced to JTCM Japanese Language School by the principal of my previous job. As JTCM has Japanese native teachers at the school, I think I’ll have chances to know in detail more about the Japanese teaching methods and Japanese culture for more so I joined the company. I also want to share the contents and knowledge I know with others as well so that’s why I started my career as a Japanese teacher.",
    q3: "What is the working  atmosphere like at Qualy Myanmar?",
    ans3: "For me, the working environment is like a warm and enjoyable place not like an upsetting work environment. The colleagues from the company treat each other with respect regardless of age. The members support each other, they also consider carefully and give advice if someone has something important to consult. ",
    q4: "Please explain the roles and responsibilities of Japanese Teacher?",
    ans4: "Perspectively, the duty of a Japanese teacher may not seem so difficult but in reality it’s not that simple. Not only teaching but also needs to monitoring the situation of students constantly. We need to recognize students' weak points and address them through specific teaching methods, while also sharing relevant cultural insights. So we need to figure out which kinds of teaching methods can make the students understand more effectively. And also need to study and learn constantly to enrich for knowledge about Japanese.",
    q5: "What kind of person do you think is suitable for the role of Japanese Teacher?",
    ans5: "In my opinion, people who are literally interested in the Japanese language, Japanese culture and are also willing to teach are suitable as a Japanese teacher. Those who want to learn basic teaching methods from native Japanese teachers, who want to upgrade their teaching skills by learning from native Japanese teachers, and who want to have a good experience of working together with Japanese people should apply at JTCM School of Qualy Myanmar.",
    q6: "Could you share an experience when you felt particularly motivated and fulfilled by your work?",
    ans6: "I felt worth working as a Japanese teacher at the time when the students that I had taught were able to employ Japanese in practice and be able to communicate well with Japanese people, and the time when they can answer the interview confidently and smoothly.",
    q7: "What are your future goals?",
    ans7: "Along my Japanese language learning journey, I've become familiar with its unique language structure, which differs from my mother language and also knew more about the traditions and cultures of Japan. My vision for the future is to acquire the Japanese teacher certificate authorized by Japan. I aspire to enhance the quality of Japanese language education for my students by providing excellent services.",
  },
];

export default interviewerData;
