const interviewerData = [
  {
    id: 1,
    no: "Interview01",
    src: "/interview01.png",
    alt: "interview01の画像",
    position: "QA Engineer",
    name: "Yadanar Kyaw Khaing",
    date: "(Joined in 2019)",
    mv_src: "/slider_img01.png",
    about: "This is about text",
    q1: "This is dummy text.",
    ans1: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q2: "This is dummy text.",
    ans2: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q3: "This is dummy text.",
    ans3: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q4: "This is dummy text.",
    ans4: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q5: "This is dummy text.",
    ans5: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q6: "This is dummy text.",
    ans6: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q7: "This is dummy text.",
    ans7: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q8: "This is dummy text.",
    ans8: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
  },
  {
    id: 2,
    no: "Interview02",
    src: "/interview02.png",
    alt: "interview02の画像",
    position: "QA Engineer",
    name: "Myo Thandar Aye",
    date: "(Joined in 2019)",
    mv_src: "/slider_img01.png",
    about: "This is about text",
    q1: "This is dummy text.",
    ans1: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q2: "This is dummy text.",
    ans2: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q3: "This is dummy text.",
    ans3: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q4: "This is dummy text.",
    ans4: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q5: "This is dummy text.",
    ans5: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q6: "This is dummy text.",
    ans6: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q7: "This is dummy text.",
    ans7: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q8: "This is dummy text.",
    ans8: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
  },
  {
    id: 3,
    no: "Interview03",
    src: "/interview03.png",
    alt: "interview03の画像",
    position: "QA Engineer",
    name: "Hnin Phyo Wai",
    date: "(Joined in 2019)",
    mv_src: "/slider_img01.png",
    about: "This is about text",
    q1: "This is dummy text.",
    ans1: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q2: "This is dummy text.",
    ans2: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q3: "This is dummy text.",
    ans3: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q4: "This is dummy text.",
    ans4: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q5: "This is dummy text.",
    ans5: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q6: "This is dummy text.",
    ans6: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q7: "This is dummy text.",
    ans7: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q8: "This is dummy text.",
    ans8: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
  },
  {
    id: 4,
    no: "Interview04",
    src: "/interview01.png",
    alt: "interview01の画像",
    position: "QA Engineer",
    name: "Mi Moe Moe Thet",
    date: "(Joined in 2019)",
    mv_src: "/slider_img01.png",
    about: "This is about text",
    q1: "This is dummy text.",
    ans1: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q2: "This is dummy text.",
    ans2: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q3: "This is dummy text.",
    ans3: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q4: "This is dummy text.",
    ans4: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q5: "This is dummy text.",
    ans5: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q6: "This is dummy text.",
    ans6: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q7: "This is dummy text.",
    ans7: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q8: "This is dummy text.",
    ans8: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
  },
  {
    id: 5,
    no: "Interview05",
    src: "/interview02.png",
    alt: "interview02の画像",
    position: "FrontEnd Engineer",
    name: "Htet Lin Oo",
    date: "(Joined in 2021)",
    mv_src: "/slider_img01.png",
    about: "This is about text",
    q1: "This is dummy text.",
    ans1: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q2: "This is dummy text.",
    ans2: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q3: "This is dummy text.",
    ans3: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q4: "This is dummy text.",
    ans4: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q5: "This is dummy text.",
    ans5: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q6: "This is dummy text.",
    ans6: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q7: "This is dummy text.",
    ans7: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q8: "This is dummy text.",
    ans8: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
  },
  {
    id: 6,
    no: "Interview06",
    src: "/interview03.png",
    alt: "interview03の画像",
    position: "Japanese Teacher",
    name: "Thin Sabai",
    date: "(Joined in 2019)",
    about: "This is about text",
    q1: "This is dummy text.",
    ans1: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q2: "This is dummy text.",
    ans2: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q3: "This is dummy text.",
    ans3: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q4: "This is dummy text.",
    ans4: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q5: "This is dummy text.",
    ans5: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q6: "This is dummy text.",
    ans6: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q7: "This is dummy text.",
    ans7: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
    q8: "This is dummy text.",
    ans8: "This is dummy text.This is dummy text.This is dummy text.This is dummy text.This is dummy text.",
  },
];

export default interviewerData;
